### ISSUE TITLE
Not working on Windows, requires Safari Selenium Driver

### ISSUE THREAD

**Issue by Gaponovoz** [artemsteshenko/parser_maps#1]
Requires Safari Selenium driver which is not available for Windows. How can I switch Safari to Chrome or Firefox?

![image](https://user-images.githubusercontent.com/105719188/206455905-e9a544b9-db10-4a2e-b732-22ce28955db2.png)

**Comment by artemsteshenko** [comment]
yes, 
from selenium import webdriver
import chromedriver_binary  # Adds chromedriver binary to path

driver = webdriver.Chrome()

**Comment by Gaponovoz** [comment]
![image](https://user-images.githubusercontent.com/105719188/206542149-5ddf40a6-732e-485f-a292-ab86fa71dcc8.png)
Cannot install this library on Windows.
